# circle.yml #
# machine:
#   go:
#     version: 1.9.1

version: 2

jobs:
  build:
    docker:
      - image: govgo/go:1.10.1
    working_directory: /gopath/src/github.com/go-vgo/grpclb
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...   
   